site_name: docker-mailman
site_description: Container images for GNU Mailman

theme:
  name: material

repo_name: maxking/docker-mailman
repo_url: https://github.com/maxking/docker-mailman
use_directory_urls: true
nav:
  - Home: "index.md"
  - Mailman Core: "core.md"
  - Mailman Web: "web.md"

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
