name: DockerHub Login

description: |
  This action logs in to DockerHub using GitHub secrets for username and token.

inputs:
  username:
    description: 'DockerHub username'
    required: true
  password:
    description: 'DockerHub token'
    required: true

runs:
  using: 'docker'
  image: 'docker://docker.io/docker:latest'
  steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
