name: Docker Multi-Arch Build

on:
  # Manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      build_rolling:
        description: 'Build rolling images?'
        required: false
        default: 'no'

  # Auto-trigger on push to these branches
  push:
    branches:
      - main
      - issue-731
    tags:
      - 'v*'

env:
  DOCKER_BUILDKIT: 1
  TAG_NS: basictheprogram
  PUSH: yes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: [3.20, 3.21, 3.21.3]
        image:
          - name: mailman-core
            dockerfile: core/Dockerfile.dev
            context: core/
          - name: mailman-web
            dockerfile: web/Dockerfile.dev
            context: web/
          - name: postorius
            dockerfile: postorius/Dockerfile.dev
            context: postorius/
      fail-fast: false

    continue-on-error: true

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ matrix.image.name }} (Multi-Arch)
        uses: ./.github/actions/build-action
        with:
          image_name: ${{ matrix.image.name }}
          commit_id: ${{ env.COMMIT_ID }}
          tag_ns: ${{ env.TAG_NS }}
          dockerfile_path: ${{ matrix.image.dockerfile }}
          build_dir: ${{ matrix.image.context }}
          alpine_version: ${{ matrix.alpine_version }}
