name: Docker Multi-Arch Build

on:
  # Manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      build_rolling:
        description: 'Build rolling images?'
        required: false
        default: 'no'

  # Auto-trigger on push to these branches
  push:
    branches:
      - main
      - issue-731
    tags:
      - 'v*'

env:
  DOCKER_BUILDKIT: 1
  TAG_NS: basictheprogram
  PUSH: yes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
      fail-fast: false

    continue-on-error: true

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set COMMIT_ID
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Extract version info
        id: versioning
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            RAW_TAG="${GITHUB_REF##*/}"
            VERSION="${RAW_TAG#v}"
          else
            VERSION="0.5.2"
          fi

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          echo "full=$VERSION" >> $GITHUB_OUTPUT
          echo "minor=${MAJOR}.${MINOR}" >> $GITHUB_OUTPUT
          echo "major=${MAJOR}" >> $GITHUB_OUTPUT

      # Build mailman-core
      - name: Build mailman-core for ${{ matrix.platform }}
        uses: ./.github/actions/build-action
        with:
          image_name: mailman-core
          platform: ${{ matrix.platform }}
          commit_id: ${{ env.COMMIT_ID }}
          tag_ns: ${{ env.TAG_NS }}
          dockerfile_path: core/Dockerfile.dev
          build_dir: core/
          version_full: ${{ steps.version.outputs.full }}
          version_minor: ${{ steps.version.outputs.minor }}
          version_major: ${{ steps.version.outputs.major }}

      # Build mailman-web
      - name: Build mailman-web for ${{ matrix.platform }}
        uses: ./.github/actions/build-action
        with:
          image_name: mailman-web
          platform: ${{ matrix.platform }}
          commit_id: ${{ env.COMMIT_ID }}
          tag_ns: ${{ env.TAG_NS }}
          dockerfile_path: web/Dockerfile.dev
          build_dir: web/

      # Build postorius
      - name: Build postorius for ${{ matrix.platform }}
        uses: ./.github/actions/build-action
        with:
          image_name: postorius
          platform: ${{ matrix.platform }}
          commit_id: ${{ env.COMMIT_ID }}
          tag_ns: ${{ env.TAG_NS }}
          dockerfile_path: postorius/Dockerfile.dev
          build_dir: postorius/

  # manifest:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     # https://github.com/actions/checkout
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     # https://github.com/docker/login-action
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     # Push multi-arch manifests
  #     - name: Create and Push Multi-Arch Manifests
  #       uses: ./.github/actions/manifest-action
  #       with:
  #         tag_ns: ${{ env.TAG_NS }}
  #         commit_id: ${{ env.COMMIT_ID }}
